### ISSUE TITLE
List items in dropdown menu

### ISSUE THREAD

**Issue by santoshmaharjan** [Jako/multiTV#141]
Hi Jako,
I am trying to achieve the following using multiTV in my website.
Create a list of items in a tab and display those items as dropdown in another tab.
In my case, I want to display the Category ID I created in a tab (screen 1) and display those saved Category IDs in another tab (screen 2) under Category dropdown menu (indicated by an arrow in the attached screen 2).
So far, I am not been able to do it. Can it be done natively? Can you please guide me.
Please see the screenshots attached.
![screen1](https://cloud.githubusercontent.com/assets/1814108/8272586/1fdeef68-1869-11e5-97e0-a6326c93a396.gif)
![screen2](https://cloud.githubusercontent.com/assets/1814108/8272587/1fe39824-1869-11e5-8489-211f10fc9f2d.gif)
Thank you.

**Comment by vmoreira** [comment]
Hello @santoshmaharjan,

Like you ask I don't know if it is possible because you want to get MultiTV values before save... but perhaps @Jako know other ways...

I do in 2 different documents in CMS what you want and make a configuration to get the values for 1st doc like this in config multiTV in 2nd doc:

'caption' => 'Element',
'type' => 'dropdown',
'elements' => '@EVAL return $modx->runSnippet('multiTV',array('tvName' =>'MultiTC','docid' =>'5','outerTpl' =>'OUTER','rowTpl' =>'@CODE:[+CategoryID+]||','display' =>'all'));'

You can personalize your own snippet in MultiTV configuration.

**Comment by santoshmaharjan** [comment]
Thanks a ton vmoreira. It worked like a charm :)
Though single quote did not work, so I replaced them with double quotes and worked.

**Comment by Jako** [comment]
@vmoreira Thanks for the solution. Have formatted the code a bit.
